services:
  - type: web
    name: freelanceconfia-backend
    env: node
    buildCommand: cd FreelanceConfía/confia-talento-latam-main && npm install && npm run build
    startCommand: node app.js
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false